/**
 * Default English resources for the HMI plugin. The same keys are listed in
 * resources/dia.txt for translation; mxResources.parse does not overwrite
 * keys that were already loaded from a translated bundle.
 */
(function()
{
	var root = (typeof globalThis !== 'undefined') ? globalThis : window;
	var Hmi = root.Hmi = root.Hmi || {};

	var Resources = {};

	Resources.DEFAULTS = {
		hmi: 'HMI / SCADA',
		hmiTab: 'HMI',
		hmiDocTriggers: 'Page Triggers',
		hmiUntrustedRun: 'This screen was not loaded from a trusted location. Run it and connect to its data sources?',
		hmiRun: 'Run Screen',
		hmiLivePreview: 'Live Preview',
		hmiInteractive: 'Interactive Preview',
		hmiSimulate: 'Simulate Data',
		hmiSources: 'Data Sources',
		hmiTags: 'Tags',
		hmiTagBrowser: 'Tag Browser',
		hmiDiagnostics: 'Diagnostics',
		hmiValidate: 'Validate',
		hmiDocs: 'HMI Help',
		hmiAllowScripts: 'Allow Scripts',
		hmiScriptsPrompt: 'This diagram contains scripts. Allow them to run?',
		hmiEnterValue: 'Enter value',
		hmiConfirmAction: 'Are you sure?',
		hmiConfirmWrite: 'Write {2} to {1}?',
		hmiPopupBlocked: 'The runtime window was blocked. Please allow popups for this site.',
		hmiConnected: 'Connected',
		hmiConnecting: 'Connecting',
		hmiDisconnected: 'Disconnected',
		hmiError: 'Error',
		hmiAlarms: 'Alarms',
		hmiAcknowledge: 'Acknowledge',
		hmiAcknowledgeAll: 'Acknowledge All',
		hmiFullscreen: 'Fullscreen',
		hmiSafetyNotice: 'HMI screens are for supervisory visualization only and must not be used for safety-critical control.',
		hmiNoSources: 'No data sources',
		hmiImportMeta2d: 'Import meta2d JSON...',
		hmiExportHtml: 'Export HMI Screen (HTML)...',
		hmiImportReportIntro: 'The following features could not be imported automatically:',

		// Format panel / shared editors
		hmiQuickAdd: 'Quick Add',
		hmiQuickLevel: 'Level ← tag',
		hmiQuickValue: 'Value ← tag',
		hmiQuickLabel: 'Label ← tag',
		hmiQuickColor: 'Color map ← tag',
		hmiQuickVisible: 'Visible ← tag',
		hmiQuickAnimation: 'Add Animation',
		hmiQuickFlow: 'Flow ← tag',
		hmiFlow: 'Flow',
		hmiFlowType: 'Flow Type',
		hmiAddItem: 'Add',
		hmiNoItems: 'No items',
		hmiMoveUp: 'Move Up',
		hmiMoveDown: 'Move Down',
		hmiShowJson: 'Show JSON',
		hmiHideJson: 'Hide JSON',
		hmiJsonFallbackHint: 'Advanced: edit the raw JSON directly.',
		hmiInvalidJson: 'Invalid JSON',
		hmiTagName: 'Tag name',
		hmiTag: 'Tag',
		hmiExpr: 'Expression',
		hmiOperator: 'Operator',
		hmiValue: 'Value',
		hmiTarget: 'Target',
		hmiTargetSelf: 'Self',
		hmiTargetCells: 'Cells',
		hmiTargetTags: 'Cell tags',
		hmiTargetLayers: 'Layers',
		hmiTargetValue: 'Target value',
		hmiTargetCellsHint: 'cell-id-1, cell-id-2',
		hmiTargetTagsHint: 'cellTag1, cellTag2',
		hmiTargetLayersHint: 'layer-id-1, layer-id-2',
		hmiTargetKeyHint: 'key',
		hmiTransform: 'Transform',
		hmiScale: 'Scale',
		hmiMap: 'Map',
		hmiInvert: 'Invert',
		hmiScript: 'Script',
		hmiInRange: 'In range',
		hmiOutRange: 'Out range',
		hmiMapEntries: 'Map entries (op:value=output;...)',
		hmiDefault: 'Default',
		hmiDecimals: 'Decimals',
		hmiShowUnit: 'Show unit',
		hmiActionType: 'Action type',
		hmiDelay: 'Delay',
		hmiReset: 'Reset value',
		hmiDuration: 'Duration',
		hmiPage: 'Page',
		hmiUrl: 'URL',
		hmiDialogTitle: 'Dialog title',
		hmiAnimationName: 'Animation name',
		hmiLabel: 'Label',
		hmiStyleJson: 'Style (JSON)',
		hmiCommand: 'Command',
		hmiEventName: 'Event name',
		hmiPayload: 'Payload',
		hmiSourceId: 'Source id',
		hmiTopic: 'Topic',
		hmiText: 'Text',
		hmiPostTo: 'Post to',
		hmiDrawioAction: 'draw.io action (JSON)',
		hmiOn: 'On',
		hmiMessageName: 'Message name',
		hmiConfirm: 'Confirm before running',
		hmiActions: 'Actions',
		hmiName: 'Name',
		hmiConditionType: 'Condition type',
		hmiConditions: 'Conditions',
		hmiElseActions: 'Else actions',
		hmiPreset: 'Preset',
		hmiAutoPlay: 'Autoplay',
		hmiRpm: 'RPM',
		hmiRpmTag: 'RPM tag',
		hmiBindings: 'Bindings',
		hmiEvents: 'Events',
		hmiTriggers: 'Triggers',
		hmiAnimations: 'Animations',
		hmiRoles: 'Roles',
		hmiAction_setProps: 'Set properties',
		hmiAction_writeTag: 'Write tag',
		hmiAction_toggleTag: 'Toggle tag',
		hmiAction_pulseTag: 'Pulse tag',
		hmiAction_navigate: 'Navigate',
		hmiAction_openUrl: 'Open URL',
		hmiAction_dialog: 'Open dialog',
		hmiAction_startAnimation: 'Start animation',
		hmiAction_pauseAnimation: 'Pause animation',
		hmiAction_stopAnimation: 'Stop animation',
		hmiAction_emit: 'Emit message',
		hmiAction_send: 'Send',
		hmiAction_notify: 'Notify',
		hmiAction_postMessage: 'Post message',
		hmiAction_script: 'Script',
		hmiAction_drawioAction: 'draw.io action',
		hmiAction_ackAlarms: 'Acknowledge alarms',
		hmiAction_playMedia: 'Play media',

		// Sources dialog
		hmiAddSource: 'Add Source',
		hmiEditSource: 'Edit Source',
		hmiSourceType: 'Type',
		hmiScope: 'Scope',
		hmiPrefix: 'Prefix',
		hmiClientId: 'Client id',
		hmiKeepalive: 'Keepalive (s)',
		hmiTopics: 'Topics',
		hmiCleanSession: 'Clean session',
		hmiInitMessage: 'Init message',
		hmiMethod: 'Method',
		hmiPollInterval: 'Poll interval',
		hmiBody: 'Body',
		hmiFormat: 'Format',
		hmiTemplate: 'Topic template',
		hmiScriptPolicyHint: 'Scripts obey the deployment script policy (may be disabled or require confirmation at runtime).',
		hmiParserScript: 'Parser script',
		hmiPreConnectScript: 'Pre-connect script',
		hmiCredentialsMode: 'Credentials',
		hmiSaveCredentialsWarning: 'Saved credentials are stored in the diagram file. Anyone who can open the file can read them.',
		hmiUsername: 'Username',
		hmiPassword: 'Password',
		hmiToken: 'Token',
		hmiParamName: 'Parameter name',
		hmiTestConnection: 'Test Connection',
		hmiReceived: 'Received',
		hmiErrors: 'Errors',
		hmiWarnings: 'Warnings',
		hmiCredentialsFor: 'Credentials for',

		// Tags dialog
		hmiAddTag: 'Add Tag',
		hmiEditTag: 'Edit Tag',
		hmiTagType: 'Type',
		hmiUnit: 'Unit',
		hmiAccess: 'Access',
		hmiMin: 'Min',
		hmiMax: 'Max',
		hmiInitial: 'Initial value',
		hmiStaleMs: 'Stale after (ms)',
		hmiLocal: 'Screen variable (no source)',
		hmiSimulation: 'Simulation',
		hmiSimKind: 'Kind',
		hmiSimPeriod: 'Period',
		hmiSimValues: 'Values',
		hmiWriteTarget: 'Write target',
		hmiWriteMode: 'Write mode',
		hmiSimMode: 'Simulation mode',
		hmiScripts: 'Scripts',
		hmiFit: 'Fit',
		hmiNav: 'Navigation',
		hmiMaxRate: 'Max update rate',
		hmiQuality: 'Bad/stale indication',
		hmiValueQuality: 'Quality',
		hmiPanZoom: 'Allow pan/zoom',
		hmiImportCsv: 'Import CSV',
		hmiExportCsv: 'Export CSV',
		hmiImportJson: 'Import JSON',
		hmiExportJson: 'Export JSON',

		// Tag browser
		hmiOverride: 'Override',
		hmiOverrideHint: 'Click the edit icon to override this value',
		hmiOverrideValue: 'Override value for',

		// Diagnostics
		hmiSourcesTab: 'Sources',
		hmiRateTab: 'Rate',
		hmiLogTab: 'Log',
		hmiWritesTab: 'Writes',
		hmiState: 'State',
		hmiLastMessage: 'Last Message',
		hmiLastError: 'Last Error',
		hmiCategory: 'Category',
		hmiFrames: 'Frames',
		hmiUpdates: 'Updates',
		hmiFlushed: 'Cells Flushed',
		hmiNoAlarms: 'No active alarms',
		hmiNoRuntime: 'The HMI runtime is not running. Start Live Preview or Run Screen first.',

		// Validator
		hmiValidateOk: 'No issues found.'
	};

	Resources.install = function()
	{
		var lines = [];

		for (var key in Resources.DEFAULTS)
		{
			if (mxResources.resources[key] == null)
			{
				lines.push(key + '=' + Resources.DEFAULTS[key]);
			}
		}

		mxResources.parse(lines.join('\n'));
	};

	Hmi.Resources = Resources;
})();
