/**
 * Default English resources for the HMI plugin. The same keys are listed in
 * resources/dia.txt for translation; mxResources.parse does not overwrite
 * keys that were already loaded from a translated bundle.
 */
(function()
{
	var root = (typeof globalThis !== 'undefined') ? globalThis : window;
	var Hmi = root.Hmi = root.Hmi || {};

	var Resources = {};

	Resources.DEFAULTS = {
		hmiHaloOutlineFollows: 'Outline shape',
		hmiHaloOutlineRect: 'Rectangle',
		hmiHaloOutlineShape: 'Follow the object\'s shape',
		hmiHaloPreset_shapeOutline: 'Shape outline',
		hmiHoverHalo: 'Hover Halo',
		hmiHaloHint: 'How interactive objects are highlighted in a running screen when the mouse is over them, when they have keyboard focus and while they are pressed.',
		hmiHaloEnabled: 'Show hover halo',
		hmiHaloStyle: 'Style',
		hmiHaloGlow: 'Glow',
		hmiHaloOutline: 'Outline',
		hmiHaloGlowOutline: 'Glow and outline',
		hmiHaloGlowSize: 'Glow size',
		hmiHaloIntensity: 'Glow intensity',
		hmiHaloLineWidth: 'Outline width',
		hmiHaloPadding: 'Outline padding',
		hmiHaloRadius: 'Corner radius',
		hmiHaloDashed: 'Dashed outline',
		hmiHaloPress: 'Stronger halo while pressed',
		hmiHaloPresets: 'Presets',
		hmiHaloPreview: 'Preview',
		hmiHaloPressColor: 'Pressed color',
		hmiHaloSameColor: 'Same color',
		hmiHaloHover: 'Hover',
		hmiHaloPressed: 'Pressed',
		hmiHaloPageDefault: 'Page default',
		hmiHaloPageSettings: 'Page Hover Halo Settings',
		hmiHaloPreset_softGlow: 'Soft glow',
		hmiHaloPreset_subtleGlow: 'Subtle glow',
		hmiHaloPreset_strongGlow: 'Strong glow',
		hmiHaloPreset_crispOutline: 'Crisp outline',
		hmiHaloPreset_dashedOutline: 'Dashed outline',
		hmiHaloPreset_glowOutline: 'Glow and outline',
		hmiHaloPreset_off: 'Off',
		hmi: 'HMI / SCADA',
		hmiTab: 'HMI',
		hmiDocTriggers: 'Page Triggers',
		hmiUntrustedRun: 'This screen was not loaded from a trusted location. Run it and connect to its data sources?',
		hmiRun: 'Run Screen',
		hmiLivePreview: 'Live Preview',
		hmiInteractive: 'Interactive Preview',
		hmiSimulate: 'Simulate Data',
		hmiSources: 'Data Sources',
		hmiTags: 'Tags',
		hmiTagBrowser: 'Tag Browser',
		hmiDiagnostics: 'Diagnostics',
		hmiValidate: 'Validate',
		hmiDocs: 'HMI Help',
		hmiAllowScripts: 'Allow Scripts',
		hmiScriptsPrompt: 'This diagram contains scripts. Allow them to run?',
		hmiEnterValue: 'Enter value',
		hmiConfirmAction: 'Are you sure?',
		hmiConfirmWrite: 'Write {2} to {1}?',
		hmiPopupBlocked: 'The runtime window was blocked. Please allow popups for this site.',
		hmiConnected: 'Connected',
		hmiConnecting: 'Connecting',
		hmiDisconnected: 'Disconnected',
		hmiError: 'Error',
		hmiAlarms: 'Alarms',
		hmiAcknowledge: 'Acknowledge',
		hmiAcknowledgeAll: 'Acknowledge All',
		hmiFullscreen: 'Fullscreen',
		hmiSafetyNotice: 'HMI screens are for supervisory visualization only and must not be used for safety-critical control.',
		hmiNoSources: 'No data sources',
		hmiImportMeta2d: 'Import meta2d JSON...',
		hmiExportHtml: 'Export HMI Screen (HTML)...',
		hmiImportReportIntro: 'The following features could not be imported automatically:',

		// Format panel / shared editors
		hmiQuickAdd: 'Quick Add',
		hmiQuickLevel: 'Level ← tag',
		hmiQuickValue: 'Value ← tag',
		hmiQuickLabel: 'Label ← tag',
		hmiQuickColor: 'Color map ← tag',
		hmiQuickVisible: 'Visible ← tag',
		hmiQuickAnimation: 'Add Animation',
		hmiQuickFlow: 'Flow ← tag',
		hmiFlow: 'Flow',
		hmiFlowType: 'Flow Type',
		hmiAddItem: 'Add',
		hmiNoItems: 'No items',
		hmiMoveUp: 'Move Up',
		hmiMoveDown: 'Move Down',
		hmiShowJson: 'Show JSON',
		hmiHideJson: 'Hide JSON',
		hmiJsonFallbackHint: 'Advanced: edit the raw JSON directly.',
		hmiInvalidJson: 'Invalid JSON',
		hmiTagName: 'Tag name',
		hmiTag: 'Tag',
		hmiExpr: 'Expression',
		hmiOperator: 'Operator',
		hmiValue: 'Value',
		hmiTarget: 'Target',
		hmiTargetSelf: 'Self',
		hmiTargetCells: 'Cells',
		hmiTargetTags: 'Cell tags',
		hmiTargetLayers: 'Layers',
		hmiTargetValue: 'Target value',
		hmiTargetCellsHint: 'cell-id-1, cell-id-2',
		hmiTargetTagsHint: 'cellTag1, cellTag2',
		hmiTargetLayersHint: 'layer-id-1, layer-id-2',
		hmiTargetKeyHint: 'key',
		hmiTransform: 'Transform',
		hmiScale: 'Scale',
		hmiMap: 'Map',
		hmiInvert: 'Invert',
		hmiScript: 'Script',
		hmiInRange: 'In range',
		hmiOutRange: 'Out range',
		hmiMapEntries: 'Map entries (op:value=output;...)',
		hmiDefault: 'Default',
		hmiDecimals: 'Decimals',
		hmiShowUnit: 'Show unit',
		hmiActionType: 'Action type',
		hmiDelay: 'Delay',
		hmiReset: 'Reset value',
		hmiDuration: 'Duration',
		hmiPage: 'Page',
		hmiUrl: 'URL',
		hmiDialogTitle: 'Dialog title',
		hmiAnimationName: 'Animation name',
		hmiLabel: 'Label',
		hmiStyleJson: 'Style (JSON)',
		hmiCommand: 'Command',
		hmiEventName: 'Event name',
		hmiPayload: 'Payload',
		hmiSourceId: 'Source id',
		hmiTopic: 'Topic',
		hmiText: 'Text',
		hmiPostTo: 'Post to',
		hmiDrawioAction: 'draw.io action (JSON)',
		hmiOn: 'On',
		hmiMessageName: 'Message name',
		hmiConfirm: 'Confirm before running',
		hmiActions: 'Actions',
		hmiName: 'Name',
		hmiConditionType: 'Condition type',
		hmiConditions: 'Conditions',
		hmiElseActions: 'Else actions',
		hmiPreset: 'Preset',
		hmiAutoPlay: 'Autoplay',
		hmiRpm: 'RPM',
		hmiRpmTag: 'RPM tag',
		hmiBindings: 'Bindings',
		hmiEvents: 'Events',
		hmiTriggers: 'Triggers',
		hmiAnimations: 'Animations',
		hmiRoles: 'Roles',
		hmiAction_setProps: 'Set properties',
		hmiAction_writeTag: 'Write tag',
		hmiAction_toggleTag: 'Toggle tag',
		hmiAction_pulseTag: 'Pulse tag',
		hmiAction_navigate: 'Navigate',
		hmiAction_openUrl: 'Open URL',
		hmiAction_dialog: 'Open dialog',
		hmiAction_startAnimation: 'Start animation',
		hmiAction_pauseAnimation: 'Pause animation',
		hmiAction_stopAnimation: 'Stop animation',
		hmiAction_emit: 'Emit message',
		hmiAction_send: 'Send',
		hmiAction_notify: 'Notify',
		hmiAction_postMessage: 'Post message',
		hmiAction_script: 'Script',
		hmiAction_drawioAction: 'draw.io action',
		hmiAction_ackAlarms: 'Acknowledge alarms',
		hmiAction_playMedia: 'Play media',

		// Sources dialog
		hmiAddSource: 'Add Source',
		hmiEditSource: 'Edit Source',
		hmiSourceType: 'Type',
		hmiScope: 'Scope',
		hmiPrefix: 'Prefix',
		hmiClientId: 'Client id',
		hmiKeepalive: 'Keepalive (s)',
		hmiTopics: 'Topics',
		hmiCleanSession: 'Clean session',
		hmiInitMessage: 'Init message',
		hmiMethod: 'Method',
		hmiPollInterval: 'Poll interval',
		hmiBody: 'Body',
		hmiFormat: 'Format',
		hmiTemplate: 'Topic template',
		hmiScriptPolicyHint: 'Scripts obey the deployment script policy (may be disabled or require confirmation at runtime).',
		hmiParserScript: 'Parser script',
		hmiPreConnectScript: 'Pre-connect script',
		hmiCredentialsMode: 'Credentials',
		hmiSaveCredentialsWarning: 'Saved credentials are stored in the diagram file. Anyone who can open the file can read them.',
		hmiUsername: 'Username',
		hmiPassword: 'Password',
		hmiToken: 'Token',
		hmiParamName: 'Parameter name',
		hmiTestConnection: 'Test Connection',
		hmiReceived: 'Received',
		hmiErrors: 'Errors',
		hmiWarnings: 'Warnings',
		hmiCredentialsFor: 'Credentials for',

		// Tags dialog
		hmiAddTag: 'Add Tag',
		hmiEditTag: 'Edit Tag',
		hmiTagType: 'Type',
		hmiUnit: 'Unit',
		hmiAccess: 'Access',
		hmiMin: 'Min',
		hmiMax: 'Max',
		hmiInitial: 'Initial value',
		hmiStaleMs: 'Stale after (ms)',
		hmiLocal: 'Screen variable (no source)',
		hmiSimulation: 'Simulation',
		hmiSimKind: 'Kind',
		hmiSimPeriod: 'Period',
		hmiSimValues: 'Values',
		hmiSimStep: 'Step',
		hmiSimInterval: 'Interval',
		hmiSimInteger: 'Integers only',
		hmiSimCode: 'Script',
		hmiAlarmDeadband: 'Deadband',
		hmiAlarmBool: 'Alarm when',
		hmiAlarmTarget: 'Target',
		hmiAlarmMinorDev: 'Minor dev.',
		hmiAlarmMajorDev: 'Major dev.',
		hmiAlarmRoc: 'Rate of change (per s)',
		hmiWriteTarget: 'Write target',
		hmiWriteMode: 'Write mode',
		hmiSimMode: 'Simulation mode',
		hmiScripts: 'Scripts',
		hmiFit: 'Fit',
		hmiNav: 'Navigation',
		hmiMaxRate: 'Max update rate',
		hmiQuality: 'Bad/stale indication',
		hmiValueQuality: 'Quality',
		hmiPanZoom: 'Allow pan/zoom',
		hmiImportCsv: 'Import CSV',
		hmiExportCsv: 'Export CSV',
		hmiImportJson: 'Import JSON',
		hmiExportJson: 'Export JSON',

		// Tag browser
		hmiOverride: 'Override',
		hmiOverrideHint: 'Click the edit icon to override this value',
		hmiOverrideValue: 'Override value for',

		// Diagnostics
		hmiSourcesTab: 'Sources',
		hmiRateTab: 'Rate',
		hmiLogTab: 'Log',
		hmiWritesTab: 'Writes',
		hmiState: 'State',
		hmiLastMessage: 'Last Message',
		hmiLastError: 'Last Error',
		hmiCategory: 'Category',
		hmiFrames: 'Frames',
		hmiUpdates: 'Updates',
		hmiFlushed: 'Cells Flushed',
		hmiNoAlarms: 'No active alarms',
		hmiNoRuntime: 'The HMI runtime is not running. Start Live Preview or Run Screen first.',

		// Animation links, substitute tags, tag browser select mode
		hmiAnimationLinks: 'Animation Links',
		hmiSubstituteTags: 'Substitute Tags',
		hmiDefineMissingTags: 'Define Missing Tags',
		hmiNoMissingTags: 'All referenced tags are already defined in the tag catalogue.',
		hmiDefineMissingHint: '{1} referenced tags are not defined in the tag catalogue. The selected tags are added to the tags of this page.',
		hmiSubstituteHint: 'Replace the tags referenced by the {1} selected object(s): links, bindings, events, triggers and animations. Leave New Name empty to keep a tag.',
		hmiSubstituteHintPage: 'Nothing is selected: the tags of all objects on this page are listed ({1} objects). Leave New Name empty to keep a tag.',
		hmiSubstituteNone: 'The selection does not reference any tags.',
		hmiSubstituteOld: 'Old Name',
		hmiSubstituteNew: 'New Name',
		hmiSubstituteNewHint: 'New tag name',
		hmiSubstituteInvalid: '"{1}" is not a valid tag name.',
		hmiType: 'Type',
		hmiDescription: 'Description',
		hmiFilter: 'Filter',
		hmiFilterHint: 'Filter, e.g. Tank* or Pump?',
		hmiView: 'View',
		hmiViewList: 'List',
		hmiViewDetails: 'Details',
		hmiSelectTag: 'Select Tag',
		hmiPickColor: 'Pick a color',
		hmiLnkNoLinks: 'No animation links',
		hmiLnkConfigure: 'Configure',
		hmiLnkRemoveAll: 'Remove All',
		hmiLnkSelectCell: 'Select one or more objects first.',
		hmiLnkTabs: 'Link categories',
		hmiLnkTabDisplay: 'Display',
		hmiLnkTabAnimation: 'Animation',
		hmiLnkTabTouch: 'Touch',
		hmiLnkTabScripts: 'Scripts',
		hmiLnkColObject: 'Object',
		hmiLnkColCommand: 'Command',
		hmiLnkColAnimation: 'Animation',
		hmiHelpLabel: 'Help: {1}',
		hmiLnkDisplayLinks: 'Display Links',
		hmiLnkTouchLinks: 'Touch Links',
		hmiLnkValueDisplay: 'Value Display',
		hmiLnkLocation: 'Location',
		hmiLnkObjectSize: 'Object Size',
		hmiLnkLineColor: 'Line Color',
		hmiLnkFillColor: 'Fill Color',
		hmiLnkTextColor: 'Text Color',
		hmiLnkPercentFill: 'Percent Fill',
		hmiLnkMiscellaneous: 'Miscellaneous',
		hmiLnkUserInputs: 'User Inputs',
		hmiLnkSliders: 'Sliders',
		hmiLnkTouchPushbuttons: 'Touch Pushbuttons',
		hmiLnkDiscrete: 'Discrete',
		hmiLnkAnalog: 'Analog',
		hmiLnkString: 'String',
		hmiLnkDiscreteAlarm: 'Discrete Alarm',
		hmiLnkAnalogAlarm: 'Analog Alarm',
		hmiLnkHorizontal: 'Horizontal',
		hmiLnkVertical: 'Vertical',
		hmiLnkHeight: 'Height',
		hmiLnkWidth: 'Width',
		hmiLnkVisibility: 'Visibility',
		hmiLnkBlink: 'Blink',
		hmiLnkOrientation: 'Orientation',
		hmiLnkDisable: 'Disable',
		hmiLnkTooltip: 'Tooltip',
		hmiLnkDiscreteValue: 'Discrete Value',
		hmiLnkAction: 'Action',
		hmiLnkShowWindow: 'Show Window',
		hmiLnkHideWindow: 'Hide Window',
		hmiLnkOutput: 'Output',
		hmiLnkInput: 'Input',
		hmiLnkTouch: 'Touch',
		hmiLnkPushbutton: 'Pushbutton',
		hmiLnkDiscreteExpression: 'Discrete Expression',
		hmiLnkAnalogExpression: 'Analog Expression',
		hmiLnkStringExpression: 'String Expression',
		hmiLnkAnalogValue: 'Analog Value',
		hmiLnkDiscreteTagname: 'Discrete Tagname',
		hmiLnkAnalogTagname: 'Analog Tagname',
		hmiLnkStringTagname: 'String Tagname',
		hmiLnkActionScript: 'Action Script',
		hmiLnkHorizontalLocation: 'Horizontal Location',
		hmiLnkVerticalLocation: 'Vertical Location',
		hmiLnkObjectHeight: 'Object Height',
		hmiLnkObjectWidth: 'Object Width',
		hmiLnkVerticalFill: 'Vertical Fill',
		hmiLnkHorizontalFill: 'Horizontal Fill',
		hmiLnkObjectBlinking: 'Object Blinking',
		hmiLnkObjectVisibility: 'Object Visibility',
		hmiLnkObjectDisabled: 'Object Disabled',
		hmiLnkObjectTooltip: 'Object Tooltip',
		hmiLnkHorizontalSlider: 'Horizontal Slider',
		hmiLnkVerticalSlider: 'Vertical Slider',
		hmiLnkWindowsToShow: 'Windows to Show when touched',
		hmiLnkWindowsToHide: 'Windows to Hide when touched',
		hmiLnkExpression: 'Expression',
		hmiLnkExprHint: 'Expression, e.g. TankLevel > 75',
		hmiLnkExprValue: 'Expression value',
		hmiLnkMovePixels: 'Move distance (pixels)',
		hmiLnkRotationDegrees: 'Rotation (degrees)',
		hmiLnkRotationPoint: 'Rotation point offset (pixels)',
		hmiLnkHeightPercent: 'Object height (% of design height)',
		hmiLnkWidthPercent: 'Object width (% of design width)',
		hmiLnkFillPercent: 'Fill percent',
		hmiLnkAtMin: 'At Min',
		hmiLnkAtMax: 'At Max',
		hmiLnkMinPercent: 'Min %',
		hmiLnkMaxPercent: 'Max %',
		hmiLnkAtLeft: 'At Left',
		hmiLnkAtRight: 'At Right',
		hmiLnkAtTop: 'At Top',
		hmiLnkAtBottom: 'At Bottom',
		hmiLnkToLeft: 'To Left',
		hmiLnkToRight: 'To Right',
		hmiLnkUp: 'Up',
		hmiLnkDown: 'Down',
		hmiLnkAtMaxCCW: 'At Max CCW',
		hmiLnkAtMaxCW: 'At Max CW',
		hmiLnkCcw: 'CCW',
		hmiLnkCw: 'CW',
		hmiLnkOffsetX: 'X offset',
		hmiLnkOffsetY: 'Y offset',
		hmiLnkAnchor: 'Anchor',
		hmiLnkTop: 'Top',
		hmiLnkMiddle: 'Middle',
		hmiLnkBottom: 'Bottom',
		hmiLnkLeft: 'Left',
		hmiLnkCenter: 'Center',
		hmiLnkRight: 'Right',
		hmiLnkDirection: 'Direction',
		hmiLnkFillRight: 'Right (fills from left)',
		hmiLnkFillLeft: 'Left (fills from right)',
		hmiLnkBackground: 'Background color',
		hmiLnkOnMessage: 'On Message',
		hmiLnkOffMessage: 'Off Message',
		hmiLnkOffColor: 'Off Color',
		hmiLnkOnColor: 'On Color',
		hmiLnkNormalColor: 'Normal Color',
		hmiLnkAlarmColor: 'Alarm Color',
		hmiLnkAlarmType: 'Alarm Type',
		hmiLnkAlarmValue: 'Value',
		hmiLnkAlarmDeviation: 'Deviation',
		hmiLnkAlarmRoc: 'Rate of Change',
		hmiLnkAlarm_value: 'Value',
		hmiLnkAlarm_deviation: 'Deviation',
		hmiLnkAlarm_roc: 'Rate of Change',
		hmiLnkColors: 'Colors',
		hmiLnkLoLo: 'Lo Lo',
		hmiLnkLo: 'Lo',
		hmiLnkHi: 'Hi',
		hmiLnkHiHi: 'Hi Hi',
		hmiLnkMinor: 'Minor Deviation',
		hmiLnkMajor: 'Major Deviation',
		hmiLnkRocColor: 'Rate of Change',
		hmiLnkBreakPoints: 'Break Points',
		hmiLnkBreakPointsHint: 'up to 10, ascending',
		hmiLnkBreakPointSingular: 'break point',
		hmiLnkBreakPointPlural: 'break points',
		hmiLnkNeedBreakPoint: 'Add at least one break point.',
		hmiLnkMaxBreakPoints: 'At most 10 break points are allowed.',
		hmiLnkAscending: 'Values must be in ascending order.',
		hmiLnkBlinkMode: 'Blink',
		hmiLnkBlinkInvisible: 'Invisible',
		hmiLnkBlinkVisible: 'Visible (alternate colors)',
		hmiLnkBlinkSpeed: 'Blink Speed',
		hmiLnkSlow: 'Slow',
		hmiLnkMedium: 'Medium',
		hmiLnkFast: 'Fast',
		hmiLnkVisibleWhen: 'Visible when',
		hmiLnkDisabledWhen: 'Disabled when',
		hmiLnkExprTrue: 'Expression is true (On)',
		hmiLnkExprFalse: 'Expression is false (Off)',
		hmiLnkTooltipMode: 'Tooltip',
		hmiLnkStaticText: 'Static text',
		hmiLnkTooltipText: 'Text',
		hmiLnkTooLong: 'Maximum length is {1} characters.',
		hmiLnkTagname: 'Tagname',
		hmiLnkKeyEquivalent: 'Key Equivalent',
		hmiLnkNone: '(none)',
		hmiLnkCtrl: 'Ctrl',
		hmiLnkShift: 'Shift',
		hmiLnkMessage: 'Message to user',
		hmiLnkSetPrompt: 'Set Prompt',
		hmiLnkResetPrompt: 'Reset Prompt',
		hmiLnkInputOnly: 'Input only (no display)',
		hmiLnkKeypad: 'Show on-screen keypad',
		hmiLnkKeyboard: 'Show on-screen keyboard',
		hmiLnkMinimum: 'Minimum',
		hmiLnkMaximum: 'Maximum',
		hmiLnkMaxGreaterMin: 'must be greater than the minimum.',
		hmiLnkNumberOrTag: 'Number or tag name',
		hmiLnkEcho: 'Echo characters',
		hmiLnkYes: 'Yes',
		hmiLnkNo: 'No',
		hmiLnkPassword: 'Password',
		hmiLnkPasswordChar: 'Password character',
		hmiLnkEncrypt: 'Encrypt password',
		hmiLnkReference: 'Reference location',
		hmiLnkPushAction: 'Action',
		hmiLnkPushDirect: 'Direct',
		hmiLnkPushReverse: 'Reverse',
		hmiLnkPushToggle: 'Toggle',
		hmiLnkPushReset: 'Reset',
		hmiLnkPushSet: 'Set',
		hmiLnkFormat: 'Format',
		hmiLnkAdvancedFormatting: 'Advanced formatting',
		hmiLnkFormatting: 'Formatting',
		hmiLnkFmtText: 'Text String',
		hmiLnkFmtReal: 'Real',
		hmiLnkFmtFixed: 'Fixed Dec. Point',
		hmiLnkFmtInteger: 'Integer',
		hmiLnkFmtExponential: 'Exponential',
		hmiLnkFmtHex: 'Hex',
		hmiLnkFmtBinary: 'Binary',
		hmiLnkFixedWidth: 'Fixed Width',
		hmiLnkPrecision: 'Precision',
		hmiLnkBitsFrom: 'Bits From',
		hmiLnkBitsTo: 'To',
		hmiLnkClear: 'Clear',
		hmiLnkScripts: 'Scripts',
		hmiLnkScript: 'Script',
		hmiLnkScriptSingular: 'script',
		hmiLnkScriptPlural: 'scripts',
		hmiLnkAddScript: 'Add Script',
		hmiLnkCheck: 'Check',
		hmiLnkScriptOk: 'Script is valid.',
		hmiLnkNeedScript: 'Add at least one script.',
		hmiLnkPeriodMin: 'The period must be at least 10 ms.',
		hmiLnkEvery: 'every',
		hmiLnkLine: 'Line',
		hmiLnkCond_onLeftDown: 'On Left Down',
		hmiLnkCond_whileLeftDown: 'While Left Down',
		hmiLnkCond_onLeftUp: 'On Left Up',
		hmiLnkCond_onLeftDouble: 'On Left Double Click',
		hmiLnkCond_onRightDown: 'On Right Down',
		hmiLnkCond_whileRightDown: 'While Right Down',
		hmiLnkCond_onRightUp: 'On Right Up',
		hmiLnkCond_onRightDouble: 'On Right Double Click',
		hmiLnkCond_onMouseOver: 'On Mouse Over',
		hmiLnkCond_whileMouseOver: 'While Mouse Over',
		hmiLnkCond_onMouseLeave: 'On Mouse Leave',
		hmiLnkWindows: 'Windows (pages)',
		hmiLnkNeedWindow: 'Select at least one window.',
		hmiLnkCurrentPage: 'current page',
		hmiLnkWindowSettings: 'Window settings of "{1}"',
		hmiLnkWindowType: 'Window type',
		hmiLnkWindowTitle: 'Title',
		hmiLnkWin_replace: 'Replace',
		hmiLnkWin_overlay: 'Overlay',
		hmiLnkWin_popup: 'Popup',
		hmiLnkWindowOtherPages: 'The window type of another page can be changed while that page is open.',
		hmiLnkRequired: 'is required.',
		hmiLnkNumberRequired: 'enter a number.',
		hmiLnkOutOfRange: 'out of range',
		hmiLnkColorInvalid: 'enter a color as #RRGGBB.',

		hmiLnkActions: 'Actions',
		hmiLnkAddChoice: 'Add option',
		hmiLnkAddCommand: 'Add command',
		hmiLnkAddProperty: 'Add property',
		hmiLnkAddSeries: 'Add series',
		hmiLnkAddState: 'Add state',
		hmiLnkAnalogStringValue: 'Analog/String Value',
		hmiLnkAnimName: 'Animation name',
		hmiLnkAnim_spin: 'Spin',
		hmiLnkAnim_pulse: 'Pulse',
		hmiLnkAnim_shake: 'Shake',
		hmiLnkAnim_fadeInOut: 'Fade in/out',
		hmiLnkAnim_blink: 'Blink',
		hmiLnkAnim_colorCycle: 'Color cycle',
		hmiLnkAnim_bounce: 'Bounce',
		hmiLnkAnim_sway: 'Sway',
		hmiLnkAnim_glow: 'Glow',
		hmiLnkAnim_custom: 'Custom (named animation)',
		hmiLnkAnimation: 'Animation',
		hmiLnkAnimationGroup: 'Animation',
		hmiLnkAnimationLinks: 'Animation Links',
		hmiLnkChoice: 'Choice',
		hmiLnkCmd_startAnimation: 'Start animation',
		hmiLnkCmd_pauseAnimation: 'Pause animation',
		hmiLnkCmd_stopAnimation: 'Stop animation',
		hmiLnkCmd_playMedia: 'Play media',
		hmiLnkCmd_pauseMedia: 'Pause media',
		hmiLnkCmd_stopMedia: 'Stop media',
		hmiLnkColor: 'Color',
		hmiLnkCommandPlural: 'commands',
		hmiLnkCommandSingular: 'command',
		hmiLnkCommands: 'Commands',
		hmiLnkCommonTargets: 'Common targets',
		hmiLnkCondition: 'Condition',
		hmiLnkConfirm: 'Confirmation text',
		hmiLnkConfirmTitle: 'Confirmation title',
		hmiLnkControl: 'Animation/Media Control',
		hmiLnkDataChange: 'Data Change',
		hmiLnkDeadband: 'Deadband',
		hmiLnkDelay: 'Delay (ms)',
		hmiLnkFlow: 'Flow',
		hmiLnkFlowType: 'Flow style',
		hmiLnkFlow_dash: 'Dashes',
		hmiLnkFlow_dots: 'Dots',
		hmiLnkFlow_beads: 'Beads',
		hmiLnkFlow_arrows: 'Arrows',
		hmiLnkFlow_liquid: 'Liquid',
		hmiLnkHidden: 'Hidden',
		hmiLnkImage: 'Image',
		hmiLnkKeep: '(keep)',
		hmiLnkLabel: 'Label',
		hmiLnkLineWidth: 'Line width',
		hmiLnkMatch: 'Match',
		hmiLnkMatchHint: '5, 0..10, 1,3,5 or *',
		hmiLnkMaxPoints: 'Max points',
		hmiLnkMedia: 'Media',
		hmiLnkMediaMode: 'Media',
		hmiLnkMediaPause: 'Pause',
		hmiLnkMediaPlay: 'Play',
		hmiLnkMessageName: 'Message name',
		hmiLnkMessageTo: 'Send to',
		hmiLnkMultiState: 'Multi-State',
		hmiLnkNeedChoice: 'add at least one option.',
		hmiLnkNeedCommand: 'add at least one command.',
		hmiLnkNeedConditionScript: 'Enter at least one script (on true, on false, while true or while false).',
		hmiLnkNeedProperty: 'add at least one property.',
		hmiLnkNeedState: 'add at least one state.',
		hmiLnkNeedWidgetData: 'Enter an expression or add a series.',
		hmiLnkObjectHint: 'Me, object id or tag:name',
		hmiLnkObjectScripts: 'Object Scripts',
		hmiLnkOnFalse: 'On false',
		hmiLnkOnTrue: 'On true',
		hmiLnkOpacity: 'Opacity',
		hmiLnkOpacityPercent: 'Opacity percent (0-100)',
		hmiLnkOpenUrl: 'Open URL',
		hmiLnkOptionPlural: 'options',
		hmiLnkOptionSingular: 'option',
		hmiLnkOptions: 'Options',
		hmiLnkPayloadExpr: 'Payload expression',
		hmiLnkPeriod: 'Period (ms)',
		hmiLnkPreset: 'Animation',
		hmiLnkPropItems: 'Properties',
		hmiLnkProperties: 'Properties',
		hmiLnkPushAdd: 'Add',
		hmiLnkPushSubtract: 'Subtract',
		hmiLnkRateExpr: 'Rate (per minute)',
		hmiLnkReverseExpr: 'Reverse when',
		hmiLnkRoles: 'Roles',
		hmiLnkRolesHint: 'comma separated, e.g. operator, admin',
		hmiLnkScriptsBand: 'Scripts',
		hmiLnkSendMessage: 'Send Message',
		hmiLnkSeries: 'Series',
		hmiLnkSeriesName: 'Name',
		hmiLnkSeriesPlural: 'series',
		hmiLnkSeriesSingular: 'series',
		hmiLnkSpeedExpr: 'Speed (1 = normal)',
		hmiLnkStatePlural: 'states',
		hmiLnkStateSingular: 'state',
		hmiLnkStates: 'States (first match wins)',
		hmiLnkStatesProps: 'States and Properties',
		hmiLnkTarget: 'Target',
		hmiLnkTargetHint: 'style:key, attr:name, prop:name, label ...',
		hmiLnkTargetInvalid: 'use style:<key>, attr:<name>, prop:<name>, label, tooltip or visible.',
		hmiLnkToBoth: 'Page and host',
		hmiLnkToHost: 'Host page',
		hmiLnkToPage: 'This page',
		hmiLnkTouchOptions: 'Touch Options',
		hmiLnkUrl: 'URL',
		hmiLnkUrlBlank: 'New tab',
		hmiLnkUrlDialog: 'Dialog',
		hmiLnkUrlSelf: 'Same tab',
		hmiLnkUrlScheme: 'only http, https and relative URLs are allowed.',
		hmiLnkUrlTarget: 'Open in',
		hmiLnkValue: 'Value',
		hmiLnkVisible: 'Visible',
		hmiLnkWhileFalse: 'While false',
		hmiLnkWhileTrue: 'While true',
		hmiLnkWidgetData: 'Widget Data',
		hmiLnkBindings: 'Bindings',
		hmiLnkKeyframes: 'Keyframe Animations',
		hmiLnkEvents: 'Event Handlers',
		hmiLnkSecurity: 'Security',
		hmiLnkHoverHalo: 'Hover Halo',
		hmiLnkTriggers: 'Object Triggers',
		hmiLnkStateMachines: 'Object State Machines',
		hmiLnkTriggersGroup: 'Triggers',
		hmiLnkValueTag: 'Value tag',
		hmiLnkAddCondition: 'Add condition',
		hmiLnkAddFrame: 'Add frame',
		hmiLnkFrames: 'Frames',
		hmiLnkAlways: 'always',
		hmiLnkSecHide: 'Hide',
		hmiLnkSecDisable: 'Disable',
		hmiLnkSecMode: 'Without the role',
		hmiLnkSecHint: 'Users without one of these roles do not see the object (Hide) or cannot use it (Disable). Leave the roles empty for no restriction.',
		hmiLnkAnd: 'AND (all)',
		hmiLnkOr: 'OR (any)',
		hmiLnkNeedAction: 'add at least one action.',
		hmiLnkNotNegative: 'must not be negative.',
		hmiLnkOnDelay: 'On delay',
		hmiLnkOffDelay: 'Off delay',
		hmiLnkStopOnError: 'Stop on error',
		hmiLnkSmStates: 'States',
		hmiLnkFrameRotation: 'Rotation',
		hmiLnkFrameOpacity: 'Opacity',
		hmiLnkFrameScale: 'Scale',
		hmiLnkFrameDx: 'Move X',
		hmiLnkFrameDy: 'Move Y',
		hmiLnkFrameLevel: 'Level',
		hmiLnkFrameFill: 'Fill',
		hmiLnkFrameStroke: 'Line',
		hmiLnkFrameFont: 'Text',
		hmiLnkFramesOnly: '(frames only)',
		hmiLnkEasing: 'Easing',
		hmiLnkEase_linear: 'Linear',
		hmiLnkEase_ease_in: 'Ease in',
		hmiLnkEase_ease_out: 'Ease out',
		hmiLnkEase_ease_in_out: 'Ease in and out',
		hmiLnkCycles: 'Cycles',
		hmiLnkInfinite: 'infinite',
		hmiLnkKeepState: 'Keep end state',
		hmiLnkNextAnimation: 'Then start',

		// Screen Settings and HMI tab
		hmiScreenSettings: 'Screen Settings',
		hmiScrTabs: 'Screen settings',
		hmiScrSourcesHint: 'The data sources of the screen: where the values of the tags come from.',
		hmiScrTagsHint: 'The tag catalogue of the screen: declare tags to add a unit, limits, alarms, a simulation or a write target.',
		hmiScrColEnabled: 'On',
		hmiScrColSource: 'Source',
		hmiScrTriggersHint: 'Triggers of the whole page: they run actions when conditions on tags become true or false.',
		hmiScrStates: 'states',
		hmiScrAddStateMachine: 'Add Page State Machine',
		hmiScrAddPageTrigger: 'Add Page Trigger',
		hmiScrRuntime: 'Runtime',
		hmiScrWindow: 'Window',
		hmiScrRuntimeHint: 'How the running screen behaves: simulation, scripts, scaling, update rate, theme and blinking.',
		hmiScrRunSection: 'Run',
		hmiScrDisplaySection: 'Display',
		hmiScrBlinkSection: 'Blink half-periods',
		hmiScrTheme: 'Theme',
		hmiScrThemeDefault: 'Default',
		hmiScrBlinkSlow: 'Slow',
		hmiScrBlinkMedium: 'Medium',
		hmiScrBlinkFast: 'Fast',
		hmiScrPositive: 'enter a number greater than 0.',
		hmiScrWindowHint: 'How this page opens when another page shows it as a window.',
		hmiScrWindowGeometry: 'Position and size',
		hmiScrWindowInvalid: 'Window: X, Y, width and height must be numbers, the width and height greater than 0.',
		hmiScrObjectsWithLinks: 'Objects with links',
		hmiScrNoLinks: 'No HMI links',
		hmiScrSummary: 'Summary',
		hmiScrLinks: 'Links',
		hmiScrDeadband: 'Deadband',
		hmiScrOnDelay: 'On delay',
		hmiScrOffDelay: 'Off delay',

		// Validator
		hmiValidateOk: 'No issues found.'
	};

	Resources.install = function()
	{
		var lines = [];

		for (var key in Resources.DEFAULTS)
		{
			if (mxResources.resources[key] == null)
			{
				lines.push(key + '=' + Resources.DEFAULTS[key]);
			}
		}

		mxResources.parse(lines.join('\n'));
	};

	Hmi.Resources = Resources;
})();
